openapi: 3.0.0
info:
  title: paths
  version: '1.0'
  description: paths
servers:
  - url: 'http://localhost:3000'
paths:
  '/path/{ole}/{kle}/{mmm}':
    get:
      summary: Your GET endpoint
      tags:
        - path
      responses: {}
      operationId: get-path
      parameters:
        - schema:
            type: string
          in: query
          name: mech
        - schema:
            type: string
          in: path
          name: mmm
          required: true
      description: ''
    parameters:
      - schema:
          type: string
        name: ole
        in: path
        required: true
      - schema:
          type: string
        name: kle
        in: path
        required: true
      - schema:
          type: string
        name: mmm
        in: path
        required: true
components:
  schemas:
    Pap:
      title: Pap
      type: object
      properties:
        id:
          type: string
      x-tags:
        - path
tags:
  - name: path
